Sourcetree
clien-devgroup/developer-tools pull request #10
Opened 2019-11-20 14:48 UTC by 27kim

source tree 추가 하여 pull request 보냅니다

2019-11-21 13:27 UTC, JeffGuKang requested changes
아주 좋은툴이죠!! master와의 Conflict를 해결해주시겠어요?

2019-11-21 13:28 UTC, JeffGuKang requested changes

2019-11-21 13:28 UTC, JeffGuKang commented on README.md
> -
이 부분 지우시면 안되요 다시 살려주세요.

2019-11-21 13:37 UTC, 27kim commented on README.md
> -
지운지도 모르고 있었네요 @.@ 살려 놨습니다

2019-11-21 22:05 UTC, herbtea30 reviewed
👍👍

2019-11-22 02:18 UTC, devyohan commented
수고하셨습니다 :)

2019-11-23 02:31 UTC, JeffGuKang approved these changes

2019-11-23 02:32 UTC, merged