Add Git Fork
clien-devgroup/developer-tools pull request #15
Opened 2019-11-24 02:15 UTC by benneykwag

Git 형상관리 프로그램 Fork 추가합니다.

2019-11-24 02:23 UTC, JeffGuKang requested changes
Conflict 해결 부탁해요.

2019-11-25 01:03 UTC, herbtea30 requested changes
Conflict나서 HEAD와 Upstream/master 표기된 부분의 삭제가 필요합니다.

2019-11-25 01:03 UTC, herbtea30 commented on README.md
> +<<<<<<< HEAD
Conflict수정과정에서 삭제되지 않을거 같습니다.

2019-11-25 01:03 UTC, herbtea30 commented on README.md
> +>>>>>>> upstream/master
이부분도 동일한 부분이구요. conflict나서 삭제해야하는부분

2019-11-25 01:06 UTC, herbtea30 requested changes
해당 부분도 동일한 부분입니다.

2019-11-25 01:06 UTC, herbtea30 commented on README.md
> +=======
conflict나서 삭제해야하는부분

2019-11-25 01:06 UTC, herbtea30 commented on README.md
> +<<<<<<< HEAD
동일합니다.

2019-11-25 01:06 UTC, herbtea30 commented on README.md
> +=======
동일한 부분

2019-11-25 01:06 UTC, herbtea30 commented on README.md
> +>>>>>>> upstream/master
동일한 부분

2019-11-25 05:37 UTC, devyohan commented on README.md
> +>>>>>>> upstream/master
윈도 환경에서만 사용할 수 있다. 부분을
윈도와 맥에서 사용 할 수 있다. 로 수정하면 좋겠습니다.

2019-12-05 15:03 UTC, herbtea30 approved these changes
Fork 스터디하면서 알게되었는데 참 좋아요

2019-12-06 01:13 UTC, JeffGuKang commented on README.md
> +>>>>>>> upstream/master
@devyohan 해당 부분은 다른 설명(Dev-C)으로 보여 다른 이슈에서 다루겠습니다~

2019-12-06 01:13 UTC, merged