Add color-picker
clien-devgroup/developer-tools pull request #2
Opened 2019-11-10 02:59 UTC by jeongjuwon

머지 부탁

2019-11-10 03:01 UTC, JeffGuKang requested changes
표도 추가 부탁합니다.

2019-11-10 03:02 UTC, chococrunch2021 reviewed
확인했습니다 windows, mac 저렇게 쓰인거는 뭐죠

2019-11-10 03:02 UTC, 27kim commented
테스트 커멘트

2019-11-10 03:02 UTC, devyohan reviewed
파일 다운로드 링크가 있으면 좋겠어요.

2019-11-10 03:02 UTC, devyohan commented on README.md
> +프론트엔드 개발을 하다보면 필수로 사용하게 되는 Color Picker.
파일 다운로드 링크가 있으면 좋겠어요.

2019-11-10 03:03 UTC, herbtea30 commented
확인했습니다

2019-11-10 03:03 UTC, wannabewize commented
다운로드 링크도 올려주세요~

2019-11-10 03:08 UTC, JeffGuKang requested changes
표도 추가 해주세요 ㅜㅜ.

2019-11-10 03:08 UTC, JeffGuKang commented on README.md
> +프론트엔드 개발을 하다보면 필수로 사용하게 되는 Color Picker.
링크 추가 되었네요.

2019-11-13 09:32 UTC, JeffGuKang approved these changes

2019-11-13 09:32 UTC, merged