add Eclipse
clien-devgroup/developer-tools pull request #3
Opened 2019-11-13 17:00 UTC by Jelcream

이렇게 하는게 맞나요??

2019-11-14 01:32 UTC, herbtea30 commented
이클립스 좋아요~

2019-11-14 01:54 UTC, JeffGuKang commented
- Commit은 대문자로 시작해주세요
- PR의 제목은 대문자로 시작해주세요
- description은 PR에 대한 설명을 적어주세요

이 부분을 업데이트 해주시면 더 좋은 PR이 될 거 같습니다. commit 같은 경우는 지난 일이라 지금 수정하실 필요는 없어요.

2019-11-14 01:56 UTC, JeffGuKang requested changes
업데이트 부탁해요

2019-11-14 01:56 UTC, JeffGuKang commented on README.md
> +Eclipse Foundation에서 개발한 오픈 소스 기반의 통합개발환경
줄바꿈이 md 파일에서는 바로 되지 않습니다. 
장점을 좀 더 설명해주시면 더 좋을거 같아요.

2019-11-14 11:18 UTC, JeffGuKang commented
@Jelcream 본 PR의 제목과 Description을 목적에 맞게 수정해주세요. 직접 수정 하실 수 있어요. PR 내용은 질문이 아니라 본인이 PR을 생성한 설명이 들어가야 합니다.

2019-11-15 08:48 UTC, JeffGuKang approved these changes
👍

2019-11-15 08:49 UTC, merged