집중력 관련 도구 추가
clien-devgroup/developer-tools pull request #4
Opened 2019-11-13 23:23 UTC by devyohan

Noizio 라는 백색 소음 애플리케이션 정보를 추가하였습니다. 확인 부탁드립니다.

2019-11-14 01:33 UTC, herbtea30 commented
표를 따로 가는것보다 밑으로 붙이는게 보기 좋을꺼 같아요.

2019-11-14 01:52 UTC, JeffGuKang commented
저도 그 부분은 고민이 되네요. 카테고리를 표에 따로 명시하는 방향으로 갈까요? 별도로 분리하는 방법이 날까요?

2019-11-14 02:03 UTC, devyohan commented
이미 있는 표에는 실제 개발에 직/간접적인 도구가 들어 있어서 별도로 빼는 것이 좋지 않을까 싶었습니다.

2019-11-14 04:32 UTC, jeongjuwon commented
저도 밑으로 붙이고 카테고리 표시하는게 좋지 않을까 싶습니다.

2019-11-14 11:23 UTC, JeffGuKang commented
목적에 따라 카테고리들이 계속 늘어나게 될텐데 한 카테고리에 내용이 1~2개만 존재하는 경우가 많아질거 같네요. 
그럼 개발에 직접 관련된거와 (개발툴들) 그 외의 것으로 구분하는게 나을까요?

2019-11-14 13:19 UTC, herbtea30 commented
핵심기능에 해당 툴의 카테고리 성격이 있는걸로 보이는데 표 하나로 가시면 그부분을 활용하면 괜찮을꺼 같고요. 두개로 가면 개발툴과 그외로 분리하심이 괜찮은거 같아요.

2019-11-15 12:33 UTC, JeffGuKang commented
@devyohan 고럼 일단 합치고 차후에 늘어나면 분리를 고민해보면 좋을 것 같습니다. conflict 해결 부탁해요

2019-11-16 05:11 UTC, JeffGuKang commented on README.md
>  | [Apple](https://www.apple.com) |  | [Noizio for macOS, iOS](#noizio) | 백색 소음 | 상용, 자연의 소리, 소리 믹스로 원하는 소음 조합 가능 | [홈페이지](https://noiz.io/)|
제작자는  noiz.io(https://noiz.io/) 로 변경해주시겠어요?

2019-11-16 05:13 UTC, JeffGuKang commented on README.md
>  | [Apple](https://www.apple.com) |  | [Noizio for macOS, iOS](#noizio) | 백색 소음 | 상용, 자연의 소리, 소리 믹스로 원하는 소음 조합 가능 | [홈페이지](https://noiz.io/)|
문서내 링크는  #Noizio-for-macOS,-iOS 을 사용하여 연결해주시면 감사하겠습니다.

2019-11-16 05:16 UTC, JeffGuKang requested changes

2019-11-16 05:16 UTC, JeffGuKang commented on README.md
> +| [Apple](https://www.apple.com) |  | [Noizio for macOS, iOS](#noizio) | 백색 소음 | 상용, 자연의 소리, 소리 믹스로 원하는 소음 조합 가능 | [홈페이지](https://noiz.io/)|
제작자는 noiz.io(https://noiz.io/) 로 변경해주시겠어요?
문서 내 링크는 #Noizio-for-macOS,-iOS 식으로 연결해주면 좋을것 같아요.

2019-11-16 05:37 UTC, devyohan commented on README.md
> +| [Apple](https://www.apple.com) |  | [Noizio for macOS, iOS](#noizio) | 백색 소음 | 상용, 자연의 소리, 소리 믹스로 원하는 소음 조합 가능 | [홈페이지](https://noiz.io/)|
수정하였습니다.

2019-11-17 01:11 UTC, JeffGuKang approved these changes

2019-11-17 01:11 UTC, merged